apiVersion: v2
name: mlflow
description: A Helm chart for MLFlow
type: application
version: 1.0.0
appVersion: 1.20.2
keywords:
  - mlflow
home: https://mlflow.org/
icon: https://mlflow.org/docs/latest/_static/MLflow-logo-final-black.png
source:
  - https://github.com/roy-ht/helm-mlflow
maintainers:
  - name: roy-ht
    email: aflc0x@gmail.com
    url: https://github.com/roy-ht
dependencies:
  - name: postgresql
    version: ~10.10.2
    repository: https://charts.bitnami.com/bitnami
    condition: db.enabled
