image:
  repository: ghcr.io/roy-ht/mlflow
  pullPolicy: IfNotPresent

replicaCount: 1
maxSurge: 1
maxUnavailable: 0
port: 80
default_artifact_root: "/opt/artifact"

postgresql:
  enabled: false

dbHost: postgresql.mlflow.svc.cluster.local
dbPort: 5432
dbUser: mlflow
dbPassword: must_change_it
dbDatabase: mlflow

s3:
  endpoint:

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  tls: []
  hosts: [mlflow.test]
  path: /

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# volumes:
#   - name: minio
#     persistentVolumeClaim:
#       claimName: minio

nodeSelector: {}

tolerations: []

affinity: {}
