apiVersion: v2
name: mlflow
description: A Helm chart for MLFlow
type: application
version: 2.1.1.1
appVersion: 2.1.1
keywords:
  - mlflow
home: https://mlflow.org/
icon: https://mlflow.org/docs/latest/_static/MLflow-logo-final-black.png
source:
  - https://github.com/roy-ht/helm-mlflow
maintainers:
  - name: roy-ht
    email: aflc0x@gmail.com
    url: https://github.com/roy-ht
dependencies:
  - name: postgresql
    version: ~11.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
