apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mlflow.name" . }}
    helm.sh/chart: {{ include "mlflow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  dbPassword: {{ .Values.secret.dbPassword | b64enc | quote }}
