name: Chart

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docker/*'
      - 'mlflow-version'
      - '.github/workflows/docker.yaml'

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # [important] chart-releaser action needs this
      - uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
