name: Chart

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docker/*'
      - 'mlflow-version'
      - '.github/workflows/docker.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: helm/chart-testing-action@v2.1.0
      - run: ct lint
  push:
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
